# -*- coding: utf-8 -*-
"""Pechkina_Kristina_Laba2_NLP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rYMQ5FHIPiowBkJp5t99E7y5vaun5T1r
"""

#подключим необходимые библиотеки
import gensim
import re

pat = re.compile("(.*)_NOUN")

#подключаем гугл диск
from google.colab import drive
drive.mount('/content/drive')

word2vec = gensim.models.KeyedVectors.load_word2vec_format("/content/drive/MyDrive/marigostra.ru_persist_cbow.txt", binary=False, unicode_errors='ignore')

pos = ["пир_NOUN"]
neg = ["хмель_NOUN"]
dist = word2vec.most_similar(positive=pos, negative=neg, topn=10)
for i in dist:
  print (i)

pos = ["агнец_NOUN"]
neg = ["бал_NOUN"]
dist = word2vec.most_similar(positive=pos, negative=neg, topn=10)
for i in dist:
 print (i)

pos = ["трапеза_NOUN"]
neg = ["ягненок_NOUN"]
dist = word2vec.most_similar(positive=pos, negative=neg, topn=10)
for i in dist:
 print (i)

pos = ["обед_NOUN"]
neg = ["ягненок_NOUN"]
dist = word2vec.most_similar(positive=pos, negative=neg, topn=10)
for i in dist:
 print (i)

pos = ["обед_NOUN"]
neg = ["ягненок_NOUN"]
dist = word2vec.most_similar(positive=pos, negative=neg, topn=10)
for i in dist:
  e = pat.match(i[0])
  if e is not None:
    print(e.group(1))